'use strict';
let overviewAll=false;
let branchId=localStorage.getItem('ledger-branch')||Admin.MAIN,branchEditing='',staffEditing='',adminSection='master',salaryMonth=new Date().toISOString().slice(0,7),attendanceDate=new Date().toISOString().slice(0,10),attendanceMonth=new Date().toISOString().slice(0,7);
function currentBranch(){return data.branches.find(b=>b.id===branchId)||data.branches[0];}
function branchWritable(){if(currentBranch().archived){notice('This branch is archived. Unarchive it in Branch master to make changes.');return false;}return true;}
function renderBranchSelector(){if(!data.branches.some(b=>b.id===branchId))branchId=data.branches[0].id;const allSelected=tab==='summary'&&overviewAll;$('#branch').innerHTML=(tab==='summary'?`<option value="ALL" ${allSelected?'selected':''}>ALL</option>`:'')+data.branches.map(b=>`<option value="${esc(b.id)}" ${!allSelected&&b.id===branchId?'selected':''}>${esc(b.name)}${b.archived?' (archived)':''}</option>`).join('');$('#add').disabled=allSelected||currentBranch().archived;}
function adminInput(k,label,v='',type='text',extra=''){return field(k,label,type,v,extra);}
function renderBranches(){const b=data.branches.find(b=>b.id===branchEditing)||{};return heading('Branch master','Add branches, maintain contact details, archive branches, or delete a branch with its records.')+`<div class="panel"><h2>${branchEditing?'Edit branch':'Add branch'}</h2><form id="branchForm"><div class="grid">${adminInput('code','Branch code *',b.code,'text','required maxlength="30"')}${adminInput('name','Branch name *',b.name,'text','required maxlength="100"')}${adminInput('manager','Manager / contact person',b.manager)}${adminInput('phone','Phone',b.phone,'tel')}${adminInput('email','Email',b.email,'email')}${adminInput('address','Address',b.address)}${adminInput('notes','Notes',b.notes)}</div><button class="primary">Save branch</button>${branchEditing?'<button type="button" id="cancelBranchEdit">Cancel edit</button>':''}</form></div><div class="panel">${table(['Code','Branch','Manager','Phone','Status','Students / staff','Actions'],data.branches.map(b=>`<tr><td>${esc(b.code)}</td><td>${esc(b.name)}</td><td>${esc(b.manager)}</td><td>${esc(b.phone)}</td><td>${b.archived?'Archived':'Active'}</td><td>${data.students.filter(s=>s.branchId===b.id).length} / ${data.staff.filter(s=>s.branchId===b.id).length}</td><td><button data-branch-open="${b.id}">Open</button><button data-branch-edit="${b.id}">Edit master</button><button data-branch-archive="${b.id}">${b.archived?'Unarchive':'Archive'}</button><button class="danger" data-branch-delete="${b.id}">Delete branch & data</button></td></tr>`).join(''))}</div><p class="setting-note">Archiving retains all records and blocks new entries. Branch deletion moves its students, payments, staff, salary transactions and attendance to Deleted records for recovery. At least one branch must remain.</p>`;}
function branchStaff(){return data.staff.filter(s=>s.branchId===branchId);}
function staffOptions(){return branchStaff().map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.code)}${s.status==='Inactive'?' (inactive)':''}</option>`).join('');}
function renderStaff(){const b=currentBranch();let html=heading(tab==='staffmaster'?'Staff master':'Staff administration',`${esc(b.name)} · Branch-wise staff master and monthly salaries.`)+`<div class="toolbar">${(tab==='staffmaster'?[]:[['salary','Salary'],['transactions','Advances & deductions']]).map(([k,n])=>`<button data-admin-section="${k}" class="${adminSection===k?'primary':''}">${n}</button>`).join('')}<button id="exportAdmin">Download staff Excel</button></div>`;
if(b.archived)html+='<p class="setting-note">Archived branch: records are available for viewing and export. Unarchive to edit.</p>';
if(adminSection==='master'){const s=data.staff.find(s=>s.id===staffEditing&&s.branchId===branchId)||{};html+=`<div class="panel"><h2>${s.id?'Edit staff':'Add staff'}</h2><form id="staffForm"><div class="grid">${adminInput('code','Staff code *',s.code,'text','required maxlength="30"')}${adminInput('name','Full name *',s.name,'text','required maxlength="100"')}${adminInput('role','Designation',s.role)}${adminInput('phone','Mobile',s.phone,'tel')}${adminInput('email','Email',s.email,'email')}${adminInput('address','Address',s.address)}${adminInput('joined','Joining date *',s.joined||today(),'date','required')}${adminInput('salary','Monthly base salary *',s.salary||0,'number','required min="0" step="0.01"')}<label>Status<select name="status">${['Active','Inactive'].map(v=>`<option ${v===s.status?'selected':''}>${v}</option>`).join('')}</select></label>${adminInput('bank','Bank / payment details',s.bank)}${adminInput('notes','Notes',s.notes)}</div><button class="primary">Save staff</button>${s.id?'<button type="button" id="cancelStaffEdit">Cancel edit</button>':''}</form></div><div class="panel">${table(['Code','Name','Designation','Mobile','Joined','Base salary','Status',''],branchStaff().map(s=>`<tr><td>${esc(s.code)}</td><td>${esc(s.name)}</td><td>${esc(s.role)}</td><td>${esc(s.phone)}</td><td>${esc(s.joined)}</td><td>${money(s.salary)}</td><td>${esc(s.status)}</td><td><button data-staff-edit="${s.id}">Edit</button></td></tr>`).join(''))}</div><p class="setting-note">Set staff to Inactive when they leave. Their salary and attendance history stays available. Changing base salary affects months without a saved salary snapshot.</p>`;}
if(adminSection==='salary'){html+=`<div class="toolbar"><label>Salary month<input type="month" id="salaryMonth" value="${salaryMonth}" required></label><button id="freezeSalary">Save salary snapshot for this month</button></div><p class="setting-note">Net salary = base + adjustments − deductions − advance repayments. An advance is cash issued separately; it reduces salary only when an Advance repayment is entered. Attendance does not automatically deduct salary. Inactive staff are shown if they have a snapshot or transactions in the month.</p><div class="panel">${table(['Staff','Base','Adjustments','Deductions','Advance repayment','Net salary','Salary paid','Due / credit','Outstanding advances'],salaryStaff().map(s=>{const p=staffPayroll(s,salaryMonth);return `<tr><td>${esc(s.name)}</td>${['base','adjustment','deductions','repayments','net','paid','due','advanceBalance'].map(k=>`<td>${money(p[k])}</td>`).join('')}</tr>`}).join(''))}</div>`;}
if(adminSection==='transactions'){html+=`<div class="panel"><h2>Record staff transaction</h2><form id="staffEntryForm"><div class="grid"><label>Staff<select name="staffId" required><option value="">Choose staff</option>${staffOptions()}</select></label><label>Type<select name="type">${['Advance','Advance repayment','Deduction','Salary payment','Salary adjustment'].map(t=>`<option>${t}</option>`).join('')}</select></label>${adminInput('date','Transaction date',today(),'date','required')}${adminInput('month','Salary / repayment month',salaryMonth,'month','required')}${adminInput('amount','Amount',undefined,'number','required min="0.01" step="0.01"')}${adminInput('reference','Reference')}${adminInput('notes','Reason / notes')}</div><button class="primary">Save transaction</button></form></div><div class="panel">${table(['Staff','Date','Month','Type','Amount','Reference','Notes',''],data.staffEntries.filter(e=>e.branchId===branchId).sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<tr><td>${esc(data.staff.find(s=>s.id===e.staffId)?.name)}</td><td>${esc(e.date)}</td><td>${esc(e.month)}</td><td>${esc(e.type)}</td><td>${money(e.amount)}</td><td>${esc(e.reference)}</td><td>${esc(e.notes)}</td><td><button class="danger" data-entry-delete="${e.id}">Delete</button></td></tr>`).join(''))}</div>`;}return html;}
function staffPayroll(s,month){const p=Admin.payroll(data,s,month);p.base=data.salarySnapshots.find(x=>x.staffId===s.id&&x.month===month)?.base??p.base;p.net=cents(p.base+p.adjustment-p.deductions-p.repayments);p.due=cents(p.net-p.paid);return p;}
function salaryStaff(){return branchStaff().filter(s=>(s.status==='Active'&&s.joined.slice(0,7)<=salaryMonth)||data.salarySnapshots.some(x=>x.staffId===s.id&&x.month===salaryMonth)||data.staffEntries.some(e=>e.staffId===s.id&&e.month===salaryMonth));}
function renderAttendance(){return heading('Staff attendance',esc(currentBranch().name)+' · Mark attendance daily and view monthly totals.')+`<div class="toolbar"><label>Date<input type="date" id="attendanceDate" value="${attendanceDate}" required></label><label>Summary month<input type="month" id="attendanceMonth" value="${attendanceMonth}" required></label><button id="exportAdmin">Download staff Excel</button></div><form id="attendanceForm" class="panel">${table(['Staff','Status','Notes'],branchStaff().filter(s=>s.joined<=attendanceDate&&(s.status==='Active'||data.attendance.some(a=>a.staffId===s.id&&a.date===attendanceDate))).map(s=>{const a=data.attendance.find(a=>a.staffId===s.id&&a.date===attendanceDate);return `<tr><td>${esc(s.name)}</td><td><select name="status_${s.id}"><option value="">Not marked</option>${Admin.statuses.map(v=>`<option ${a?.status===v?'selected':''}>${v}</option>`).join('')}</select></td><td><input name="notes_${s.id}" maxlength="500" value="${esc(a?.notes)}" aria-label="Notes for ${esc(s.name)}"></td></tr>`}).join(''))}<button class="primary">Save attendance</button><p class="setting-note">Not marked removes an existing entry for that date. Changes are recorded in Activity history. Attendance is not an automatic payroll deduction.</p></form><div class="panel"><h2>Monthly attendance · ${esc(attendanceMonth)}</h2>${table(['Staff',...Admin.statuses,'Marked days'],branchStaff().map(s=>{const aa=data.attendance.filter(a=>a.staffId===s.id&&a.date.startsWith(attendanceMonth));return `<tr><td>${esc(s.name)}</td>${Admin.statuses.map(v=>`<td>${aa.filter(a=>a.status===v).length}</td>`).join('')}<td>${aa.length}</td></tr>`}).join(''))}</div>`;}
function adminEvent(action){return{action,subject:currentBranch().name,details:'Branch: '+currentBranch().code};}
function bindAdmin(){
 $('#branchForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),n=clone(),old=n.branches.find(b=>b.id===branchEditing),b={...old,id:old?.id||uid(),archived:old?.archived||false,fees:old?.fees||{}};for(const k of ['code','name','manager','phone','email','address','notes'])b[k]=String(f.get(k)||'').trim();if(old)n.branches[n.branches.indexOf(old)]=b;else n.branches.push(b);if(await commit(n)){branchEditing='';render()}});
 $('#cancelBranchEdit')?.addEventListener('click',()=>{branchEditing='';render()});$('#cancelStaffEdit')?.addEventListener('click',()=>{staffEditing='';render()});
 $('#staffForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!branchWritable())return;const f=new FormData(e.target),n=clone(),old=n.staff.find(s=>s.id===staffEditing&&s.branchId===branchId),s={...old,id:old?.id||uid(),branchId};for(const k of ['code','name','role','phone','email','address','joined','status','bank','notes'])s[k]=String(f.get(k)||'').trim();s.salary=cents(Number(f.get('salary')));if(old)n.staff[n.staff.indexOf(old)]=s;else n.staff.push(s);if(await commit(n)){staffEditing='';render()}});
 $('#salaryMonth')?.addEventListener('change',e=>{if(e.target.value)salaryMonth=e.target.value;render()});
 $('#freezeSalary')?.addEventListener('click',async()=>{if(!branchWritable())return;const n=clone();for(const s of salaryStaff())if(!n.salarySnapshots.some(x=>x.staffId===s.id&&x.month===salaryMonth))n.salarySnapshots.push({id:uid(),staffId:s.id,branchId,month:salaryMonth,base:s.salary});await commit(n,{event:adminEvent('Salary snapshot saved')});});
 $('#staffEntryForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!branchWritable())return;const f=new FormData(e.target),n=clone(),entry={id:uid(),branchId};for(const k of ['staffId','type','date','month','reference','notes'])entry[k]=String(f.get(k)||'').trim();entry.amount=cents(Number(f.get('amount')));n.staffEntries.push(entry);if(entry.type==='Advance repayment'&&Admin.payroll(n,n.staff.find(s=>s.id===entry.staffId),entry.month).advanceBalance<0)return notice('Repayment exceeds outstanding advances.');await commit(n)});
 $('#attendanceDate')?.addEventListener('change',e=>{if(e.target.value)attendanceDate=e.target.value;render()});$('#attendanceMonth')?.addEventListener('change',e=>{if(e.target.value)attendanceMonth=e.target.value;render()});
 $('#attendanceForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!branchWritable())return;const f=new FormData(e.target),n=clone();for(const s of branchStaff().filter(s=>s.joined<=attendanceDate&&(s.status==='Active'||data.attendance.some(a=>a.staffId===s.id&&a.date===attendanceDate)))){const status=f.get('status_'+s.id),old=n.attendance.find(a=>a.staffId===s.id&&a.date===attendanceDate);if(!status)n.attendance=n.attendance.filter(a=>a!==old);else{const a={id:old?.id||uid(),staffId:s.id,branchId,date:attendanceDate,status,notes:String(f.get('notes_'+s.id)||'').trim()};if(old)n.attendance[n.attendance.indexOf(old)]=a;else n.attendance.push(a)}}await commit(n)});
 $('#exportAdmin')?.addEventListener('click',exportAdmin);$('#resetLedger')?.addEventListener('click',resetLedger);
}
async function adminClick(b){try{
 if(b.dataset.adminSection){adminSection=b.dataset.adminSection;render()}
 if(b.dataset.branchEdit){branchEditing=b.dataset.branchEdit;render()}
 if(b.dataset.branchOpen){branchId=b.dataset.branchOpen;localStorage.setItem('ledger-branch',branchId);render()}
 if(b.dataset.branchArchive){const n=clone(),x=n.branches.find(x=>x.id===b.dataset.branchArchive);x.archived=!x.archived;if(!x.archived||confirm('Archive '+x.name+'? Records are retained and editing is disabled.'))await commit(n)}
 if(b.dataset.branchDelete){const n=clone(),x=n.branches.find(x=>x.id===b.dataset.branchDelete);if(confirm('Delete '+x.name+' and ALL its students, payments, staff, salary transactions and attendance, across every year? A restorable copy is kept in Activity history.')){Admin.removeBranch(n,x.id);n.salarySnapshots=n.salarySnapshots.filter(s=>s.branchId!==x.id);await commit(n)}}
 if(b.dataset.staffEdit){staffEditing=b.dataset.staffEdit;adminSection='master';render()}
 if(b.dataset.entryDelete&&branchWritable()){const n=clone(),entry=n.staffEntries.find(e=>e.id===b.dataset.entryDelete);if(confirm('Delete this staff transaction? Keep a JSON backup for recovery.')){n.staffEntries=n.staffEntries.filter(e=>e.id!==entry.id);if(entry.type==='Advance'&&Admin.payroll(n,n.staff.find(s=>s.id===entry.staffId),entry.month).advanceBalance<0)return notice('Remove related advance repayments first.');await commit(n)}}
 }catch(e){notice(e.message)}}
function adminSheets(){const staff=branchStaff(),ids=new Set(staff.map(s=>s.id));return{'Branch master':[['Code','Branch','Manager','Phone','Email','Address','Archived'],...data.branches.filter(b=>b.id===branchId).map(b=>[b.code,b.name,b.manager,b.phone,b.email,b.address,b.archived?'Yes':'No'])],'Staff master':[['Branch','Code','Name','Designation','Phone','Email','Address','Joining date','Status','Base salary','Bank / payment details','Notes'],...staff.map(s=>[currentBranch().name,s.code,s.name,s.role,s.phone,s.email,s.address,s.joined,s.status,s.salary,s.bank,s.notes])],'Staff transactions':[['Branch','Staff','Date','Month','Type','Amount','Reference','Notes'],...data.staffEntries.filter(e=>ids.has(e.staffId)).map(e=>[currentBranch().name,data.staff.find(s=>s.id===e.staffId)?.name,e.date,e.month,e.type,e.amount,e.reference,e.notes])],'Staff attendance':[['Branch','Staff','Date','Status','Notes'],...data.attendance.filter(a=>ids.has(a.staffId)).map(a=>[currentBranch().name,data.staff.find(s=>s.id===a.staffId)?.name,a.date,a.status,a.notes])],'Salary summary':[['Branch','Staff','Month','Base','Adjustments','Deductions','Advance repayment','Net salary','Salary paid','Due / credit','Advance balance'],...salaryStaff().map(s=>{const p=staffPayroll(s,salaryMonth);return[currentBranch().name,s.name,salaryMonth,p.base,p.adjustment,p.deductions,p.repayments,p.net,p.paid,p.due,p.advanceBalance]})]};}
function exportAdmin(){activity('Staff Excel downloaded',currentBranch().name,'Month: '+salaryMonth,'');download(makeWorkbook(adminSheets()),'staff-'+currentBranch().code+'-'+salaryMonth+'.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
async function resetLedger(){
 if(OneDrive.enabled()&&!cloudLoaded)return notice('Connect and load the shared OneDrive ledger before resetting it.');
 const shared=OneDrive.enabled()||folder;
 if(!confirm((shared?'Delete ALL records and history from the connected shared ledger? Other devices must reload it.':'Delete ALL records and history saved in this browser? This does not change OneDrive.')+' This removes all branches, students, payments, staff, salaries, attendance and deleted records. Download a JSON backup first.'))return;
 if(prompt('Type RESET ALL to confirm permanent removal:')!=='RESET ALL')return;
 const n=initial();n.resetAt=new Date().toISOString();n.school=data.school;n.currency=data.currency;Admin.validate(n);Performance.normalize(n);
 if(await commit(n,{reset:true})){branchId=Admin.MAIN;branchEditing='';staffEditing='';year=Object.keys(data.years)[0];render();notice(shared?'Shared ledger reset. On every other device use Settings → Connect folder / reload cloud data (or Reload folder data). Old backups still contain the previous records.':'Browser ledger reset.');}
}
