'use strict';
// Branch and staff data travel in the same versioned ledger as admissions.
const Admin=(()=>{
 const MAIN='00000000-0000-4000-8000-000000000001';
 const statuses=['Present','Absent','Half day','Paid leave','Unpaid leave','Holiday','Weekly off'];
 const validId=s=>typeof s==='string'&&/^[0-9a-f-]{36}$/i.test(s);
 const round=n=>Math.round((n+Number.EPSILON)*100)/100;
 const dateOK=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
 function normalize(d){
  if(!d||!Array.isArray(d.students))return;
  d.branches??=[{id:MAIN,code:'MAIN',name:'Main branch',address:'',phone:'',email:'',manager:'',notes:'',archived:false,fees:{}}];
  d.staff??=[];d.staffEntries??=[];d.attendance??=[];d.salarySnapshots??=[];
  for(const s of d.students)s.branchId??=MAIN;
  for(const x of d.deletedRecords||[])if(x.kind==='student')x.student.branchId??=MAIN;
 }
 function validate(d){normalize(d);const ids=new Set(),staffIds=new Set();
  for(const key of ['branches','staff','staffEntries','attendance','salarySnapshots'])if(!Array.isArray(d[key]))throw Error('Invalid '+key);
  if(!d.branches.length)throw Error('Keep at least one branch.');
  for(const b of d.branches){if(!b||!validId(b.id)||ids.has(b.id)||!b.name?.trim()||!b.code?.trim()||typeof b.archived!=='boolean'||!b.fees||typeof b.fees!=='object')throw Error('Invalid branch master');ids.add(b.id);for(const [y,fees] of Object.entries(b.fees)){if(!d.years[y])throw Error('Unknown branch fee year');for(const c of classes)if(!Number.isFinite(fees[c])||fees[c]<0)throw Error('Invalid branch fee');}}
  if(new Set(d.branches.map(b=>b.code.toLowerCase())).size!==d.branches.length)throw Error('Branch codes must be unique.');
  for(const s of d.students)if(!ids.has(s.branchId))throw Error('Student branch is missing.');
  for(const s of d.staff){if(!s||!validId(s.id)||staffIds.has(s.id)||!ids.has(s.branchId)||!s.name?.trim()||!s.code?.trim()||!Number.isFinite(s.salary)||s.salary<0||!['Active','Inactive'].includes(s.status)||!dateOK(s.joined))throw Error('Invalid staff master');staffIds.add(s.id);}
  const codes=new Set();for(const s of d.staff){const k=s.branchId+'|'+s.code.toLowerCase();if(codes.has(k))throw Error('Staff code already exists in this branch.');codes.add(k);}
  const entryIds=new Set();for(const e of d.staffEntries){const s=d.staff.find(s=>s.id===e.staffId);if(!validId(e.id)||!s||s.branchId!==e.branchId||entryIds.has(e.id)||!dateOK(e.date)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(e.month)||!['Advance','Advance repayment','Deduction','Salary payment','Salary adjustment'].includes(e.type)||!Number.isFinite(e.amount)||e.amount<=0)throw Error('Invalid staff transaction');entryIds.add(e.id);}
  const snapshotKeys=new Set();for(const x of d.salarySnapshots){const st=d.staff.find(s=>s.id===x.staffId),k=x.staffId+'|'+x.month;if(!validId(x.id)||!st||st.branchId!==x.branchId||snapshotKeys.has(k)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(x.month)||!Number.isFinite(x.base)||x.base<0)throw Error('Invalid salary snapshot');snapshotKeys.add(k);}
  const attendanceKeys=new Set();for(const a of d.attendance){const s=d.staff.find(s=>s.id===a.staffId),k=a.staffId+'|'+a.date;if(!validId(a.id)||!s||s.branchId!==a.branchId||attendanceKeys.has(k)||!dateOK(a.date)||!statuses.includes(a.status))throw Error('Invalid staff attendance');attendanceKeys.add(k);}
  for(const x of d.deletedRecords||[])if(x.kind==='branch'&&(!x.branch||!Array.isArray(x.students)||!Array.isArray(x.payments)||!Array.isArray(x.staff)||!Array.isArray(x.staffEntries)||!Array.isArray(x.attendance)))throw Error('Invalid deleted branch');
 }
 function fees(d,s){return d.branches.find(b=>b.id===s.branchId)?.fees?.[s.year]||d.years[s.year].fees;}
 function payroll(d,s,month){const ee=d.staffEntries.filter(e=>e.staffId===s.id&&e.month===month),sum=t=>round(ee.filter(e=>e.type===t).reduce((a,e)=>a+e.amount,0));const base=s.salary,adjustment=sum('Salary adjustment'),deductions=sum('Deduction'),repayments=sum('Advance repayment'),paid=sum('Salary payment');return{base,adjustment,deductions,repayments,net:round(base+adjustment-deductions-repayments),paid,due:round(base+adjustment-deductions-repayments-paid),advanceBalance:round(d.staffEntries.filter(e=>e.staffId===s.id).reduce((n,e)=>n+(e.type==='Advance'?e.amount:e.type==='Advance repayment'?-e.amount:0),0))};}
 function removeBranch(d,id){if(d.branches.length<=1)throw Error('Keep at least one branch.');const branch=d.branches.find(b=>b.id===id);if(!branch)throw Error('Branch not found.');const students=d.students.filter(s=>s.branchId===id),ss=new Set(students.map(s=>s.id));const copy={id:crypto.randomUUID(),kind:'branch',deletedAt:new Date().toISOString(),branch:structuredClone(branch),students:structuredClone(students),payments:structuredClone(d.payments.filter(p=>ss.has(p.student))),staff:structuredClone(d.staff.filter(s=>s.branchId===id)),staffEntries:structuredClone(d.staffEntries.filter(e=>e.branchId===id)),attendance:structuredClone(d.attendance.filter(a=>a.branchId===id)),salarySnapshots:structuredClone(d.salarySnapshots.filter(a=>a.branchId===id))};d.deletedRecords.push(copy);d.branches=d.branches.filter(b=>b.id!==id);d.students=d.students.filter(s=>s.branchId!==id);d.payments=d.payments.filter(p=>!ss.has(p.student));for(const k of ['staff','staffEntries','attendance','salarySnapshots'])d[k]=d[k].filter(s=>s.branchId!==id);return copy;}
 function restoreBranch(d,x){if(d.branches.some(b=>b.id===x.branch.id||b.code.toLowerCase()===x.branch.code.toLowerCase()))throw Error('Branch ID or code already exists.');if(Object.keys(x.branch.fees||{}).some(y=>!d.years[y])||x.students.some(s=>!d.years[s.year]))throw Error('Restore the missing academic years first.');for(const k of ['students','payments','staff','staffEntries'])if(x[k].some(s=>d[k].some(t=>s.id===t.id)))throw Error('Restore conflict in '+k);d.branches.push(structuredClone(x.branch));for(const k of ['students','payments','staff','staffEntries','attendance','salarySnapshots'])d[k].push(...structuredClone(x[k]||[]));d.deletedRecords=d.deletedRecords.filter(t=>t.id!==x.id);}
 function changes(before,after){const out=[],emit=(a,s,detail)=>out.push(History.event(after.datasetId,a,s,detail,''));for(const key of ['branches','staff','staffEntries','attendance']){for(const x of after[key]||[]){const old=(before[key]||[]).find(t=>t.id===x.id);if(JSON.stringify(old)!==JSON.stringify(x))emit(key==='branches'?(old?(x.archived&&!old.archived?'Branch archived':!x.archived&&old.archived?'Branch unarchived':'Branch updated'):'Branch added'):key==='staff'?(old?'Staff updated':'Staff added'):key==='attendance'?(old?'Attendance updated':'Attendance marked'):'Staff transaction recorded',x.name||after.staff.find(s=>s.id===x.staffId)?.name||x.id,'Branch: '+(after.branches.find(b=>b.id===x.branchId||b.id===x.id)?.name||'')+(x.type?'; '+x.type+': '+x.amount+'; month: '+x.month:'')+(x.status&&key==='attendance'?'; '+x.date+': '+x.status:''));}for(const x of before[key]||[])if(!(after[key]||[]).some(t=>t.id===x.id))emit(key==='branches'?'Branch deleted':key==='staff'?'Staff removed':key==='attendance'?'Attendance removed':'Staff transaction deleted',x.name||before.staff.find(s=>s.id===x.staffId)?.name||x.id,'Branch data removed from active records.');}return out;}
 return{MAIN,statuses,normalize,validate,fees,payroll,removeBranch,restoreBranch,changes,dateOK};
})();
