'use strict';
/* Public-client OAuth with PKCE: never put a Microsoft client secret in this app. */
const OneDrive=(()=>{
 const CONFIG='ledger-onedrive-config',TOKEN='ledger-onedrive-token',PENDING='ledger-onedrive-pkce';
 let config;try{config=JSON.parse(localStorage.getItem(CONFIG))||{clientId:'',tenant:'common',path:'Preschool Records',enabled:false}}catch{config={clientId:'',tenant:'common',path:'Preschool Records',enabled:false}}
 const redirect=()=>location.origin+location.pathname;
 const base=()=>`https://login.microsoftonline.com/${encodeURIComponent(config.tenant||'common')}/oauth2/v2.0`;
 const b64=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
 let etag=null,itemId=null;
 function saveConfig(c){if(!/^[0-9a-f-]{36}$/i.test(c.clientId))throw Error('Enter a valid Microsoft Application (client) ID.');const path=c.path.trim().replace(/^\/+|\/+$/g,'');if(!path||path.split('/').some(p=>!p||/["*:<>?\\|]/.test(p)||p==='.'||p==='..'))throw Error('Enter a folder path such as Preschool Records or School/Admissions.');if(!/^(common|consumers|organizations|[0-9a-f-]{36})$/i.test(c.tenant))throw Error('Use common, consumers, organizations or your tenant ID.');if(c.clientId!==config.clientId||c.tenant!==config.tenant)sessionStorage.removeItem(TOKEN);config={...c,path};etag=null;itemId=null;localStorage.setItem(CONFIG,JSON.stringify(config))}
 function enabled(){return config.enabled}
 function signedIn(){try{return !!JSON.parse(sessionStorage.getItem(TOKEN))?.access_token}catch{return false}}
 async function login(){if(!config.clientId)throw Error('Save the Microsoft app settings first.');if(location.protocol!=='https:'&&location.hostname!=='localhost')throw Error('Open the app on HTTPS or localhost before signing in.');const verifier=b64(crypto.getRandomValues(new Uint8Array(48))),state=b64(crypto.getRandomValues(new Uint8Array(24))),challenge=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));const pending=JSON.stringify({verifier,state,redirect:redirect(),at:Date.now()});sessionStorage.setItem(PENDING,pending);localStorage.setItem(PENDING,pending);const q=new URLSearchParams({client_id:config.clientId,response_type:'code',redirect_uri:redirect(),response_mode:'query',scope:'https://graph.microsoft.com/Files.ReadWrite offline_access',state,code_challenge:challenge,code_challenge_method:'S256'});location.assign(base()+'/authorize?'+q)}
 function authError(t){const text=t.error_description||t.error||'Microsoft sign-in failed.';let help='';if(/AADSTS50011|redirect_uri/i.test(text))help=' In Microsoft Entra → Authentication, add '+redirect()+' as a Single-page application (SPA) redirect URI.';else if(/AADSTS9002326|AADSTS9002325|AADSTS7000218|client_secret/i.test(text))help=' Register this website under Single-page application (SPA), not Web. This app does not use a client secret.';else if(/AADSTS700016|AADSTS7000215|invalid_client/i.test(text))help=' Check the Application (client) ID, account type and tenant in your Microsoft registration.';else if(/AADSTS65001|consent_required|AADSTS90094/i.test(text))help=' Grant Microsoft Graph Files.ReadWrite delegated permission; your school administrator may need to approve consent.';return text+help}
 async function exchange(fields){const previous=JSON.parse(sessionStorage.getItem(TOKEN)||'null');let r;try{r=await fetch(base()+'/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:config.clientId,...fields})})}catch{throw Error('Microsoft sign-in could not finish. Check internet access and register '+redirect()+' as a Single-page application (SPA) redirect URI in Microsoft Entra → Authentication.');}const t=await r.json();if(!r.ok)throw Error(authError(t));if(!t.refresh_token&&fields.grant_type==='refresh_token')t.refresh_token=previous?.refresh_token;t.expires_at=Date.now()+t.expires_in*1000;sessionStorage.setItem(TOKEN,JSON.stringify(t));return t}
 async function callback(){const q=new URLSearchParams(location.search);if(!q.has('code')&&!q.has('error'))return false;const pending=JSON.parse(sessionStorage.getItem(PENDING)||localStorage.getItem(PENDING)||'null');history.replaceState(null,'',location.pathname+location.hash);sessionStorage.removeItem(PENDING);localStorage.removeItem(PENDING);if(!pending||q.get('state')!==pending.state||Date.now()-pending.at>15*60*1000)throw Error('Sign-in session expired or did not match. Please sign in again.');if(q.has('error'))throw Error(authError({error:q.get('error'),error_description:q.get('error_description')}));await exchange({grant_type:'authorization_code',code:q.get('code'),redirect_uri:pending.redirect,code_verifier:pending.verifier});return true}
 async function token(){let t;try{t=JSON.parse(sessionStorage.getItem(TOKEN))}catch{}if(!t)throw Error('Sign in to Microsoft in Settings before saving to OneDrive.');if(t.expires_at<Date.now()+60000){if(!t.refresh_token)throw Error('Your Microsoft session expired. Sign in again.');try{t=await exchange({grant_type:'refresh_token',refresh_token:t.refresh_token,scope:'https://graph.microsoft.com/Files.ReadWrite offline_access'})}catch{sessionStorage.removeItem(TOKEN);throw Error('Your Microsoft session expired. Sign in again.')}}return t.access_token}
 async function api(path,options={}){const t=await token();let r;try{r=await fetch('https://graph.microsoft.com/v1.0'+path,{...options,headers:{Authorization:'Bearer '+t,...options.headers}})}catch{throw Error('OneDrive is unreachable. Check your internet connection; changes were not saved.')}return r}
 async function error(r){let d;try{d=await r.json()}catch{}throw Error(d?.error?.message||`OneDrive request failed (${r.status}).`)}
 const folderPath=()=>config.path.split('/').map(encodeURIComponent).join('/');
 async function folder(create=false){if(config.folderId){const selected=await api('/me/drive/items/'+encodeURIComponent(config.folderId));if(selected.status===404)throw Error('The remembered OneDrive folder is unavailable in this account. Browse OneDrive and select it again.');if(!selected.ok)await error(selected);const d=await selected.json();if(!d.folder)throw Error('The selected item is not a folder. Browse OneDrive again.');return d;}let r=await api('/me/drive/root:/'+folderPath());if(r.status===404&&create){const root=await api('/me/drive/root');if(!root.ok)await error(root);let parent=(await root.json()).id;for(const name of config.path.split('/')){const list=await api(`/me/drive/items/${encodeURIComponent(parent)}:/${encodeURIComponent(name)}`);if(list.ok){const d=await list.json();if(!d.folder)throw Error(name+' is a file, not a folder.');parent=d.id}else if(list.status===404){const made=await api(`/me/drive/items/${encodeURIComponent(parent)}/children`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!made.ok)await error(made);parent=(await made.json()).id}else await error(list)}return {id:parent};}if(!r.ok)await error(r);const d=await r.json();if(!d.folder)throw Error('The selected OneDrive path is not a folder.');return d}

 async function listFolders(id=null){
  const endpoint=id?'/me/drive/items/'+encodeURIComponent(id):'/me/drive/root';
  const meta=await api(endpoint+'?$select=id,name,folder');if(!meta.ok)await error(meta);const current=await meta.json();if(!current.folder)throw Error('This item is not a folder.');
  let path='/me/drive/items/'+encodeURIComponent(current.id)+'/children?$select=id,name,folder&$top=200';const children=[];
  while(path){const r=await api(path);if(!r.ok)await error(r);const page=await r.json();children.push(...(page.value||[]).filter(item=>item.folder));path=null;if(page['@odata.nextLink']){const next=new URL(page['@odata.nextLink']);if(next.origin!=='https://graph.microsoft.com'||!next.pathname.startsWith('/v1.0/'))throw Error('OneDrive returned an unexpected folder-list address.');path=next.pathname.slice('/v1.0'.length)+next.search;}}
  children.sort((a,b)=>a.name.localeCompare(b.name));return {current,children};
 }
 async function createFolder(parentId,name){name=name.trim();if(!name||name==='.'||name==='..'||/["*:<>?\\|/]/.test(name))throw Error('Enter a folder name without /, \\, or special characters.');const r=await api('/me/drive/items/'+encodeURIComponent(parentId)+'/children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok)await error(r);return r.json();}
 function selectFolder(item,path){if(!item?.id||!item.folder||!path)throw Error('Choose a folder inside OneDrive.');config={...config,path,folderId:item.id,enabled:false};etag=null;itemId=null;localStorage.setItem(CONFIG,JSON.stringify(config));}
 async function read(){const f=await folder(false);const r=await api(`/me/drive/items/${encodeURIComponent(f.id)}:/preschool-records.json`);if(r.status===404){etag=null;itemId=null;return null}if(!r.ok)await error(r);const meta=await r.json();const content=await fetch(meta['@microsoft.graph.downloadUrl']);if(!content.ok)await error(content);const d=await content.json();etag=meta.eTag;itemId=meta.id;return d}
 async function write(d,revision){const f=await folder(false);const r=await api(`/me/drive/items/${encodeURIComponent(f.id)}:/preschool-records.json`);if(r.ok){const meta=await r.json();if(!etag||meta.eTag!==etag)throw Error('OneDrive records changed. Reload cloud data in Settings before editing.');const content=await fetch(meta['@microsoft.graph.downloadUrl']);if(!content.ok)await error(content);if((await content.json()).revision!==revision)throw Error('OneDrive records changed. Reload cloud data first.');const written=await api(`/me/drive/items/${encodeURIComponent(meta.id)}/content`,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':meta.eTag},body:JSON.stringify(d)});if(written.status===412)throw Error('Someone changed the OneDrive file during your save. Reload cloud data and try again.');if(!written.ok)await error(written);const updated=await written.json();etag=updated.eTag;itemId=updated.id;}else if(r.status===404){if(revision!==null)throw Error('The OneDrive records file was removed. Reload before saving.');const upload=await api(`/me/drive/items/${encodeURIComponent(f.id)}:/preschool-records.json:/createUploadSession`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item:{'@microsoft.graph.conflictBehavior':'fail',name:'preschool-records.json'}})});if(!upload.ok)await error(upload);const session=await upload.json(),bytes=new TextEncoder().encode(JSON.stringify(d)),chunkSize=320*1024*10;let updated;for(let start=0;start<bytes.length;start+=chunkSize){const end=Math.min(start+chunkSize,bytes.length);const written=await fetch(session.uploadUrl,{method:'PUT',headers:{'Content-Type':'application/octet-stream','Content-Range':`bytes ${start}-${end-1}/${bytes.length}`},body:bytes.slice(start,end)});if(!written.ok)await error(written);updated=await written.json();}etag=updated.eTag;itemId=updated.id;}else await error(r)}
 function setEnabled(value){config.enabled=!!value;localStorage.setItem(CONFIG,JSON.stringify(config))}
 function disable(){config.enabled=false;localStorage.setItem(CONFIG,JSON.stringify(config));sessionStorage.removeItem(TOKEN);etag=null;itemId=null}
 return{get config(){return {...config}},redirect,saveConfig,enabled,signedIn,login,callback,folder,listFolders,createFolder,selectFolder,read,write,setEnabled,disable};
})();
