'use strict';
const Marksheet=(()=>{
 const enc=new TextEncoder(),x=v=>String(v??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const logo='assets/little-wings-logo.jpg';
 async function bytes(url){const r=await fetch(url);if(!r.ok)throw Error('Could not load the report logo. Refresh online and retry.');return new Uint8Array(await r.arrayBuffer());}
 function zip(files){const crc=b=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0};let offset=0;const chunks=[],central=[];for(const [path,value] of Object.entries(files)){const name=enc.encode(path),body=typeof value==='string'?enc.encode(value):value,check=crc(body),h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,check,true);v.setUint32(18,body.length,true);v.setUint32(22,body.length,true);v.setUint16(26,name.length,true);chunks.push(h,name,body);const c=new Uint8Array(46),w=new DataView(c.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,check,true);w.setUint32(20,body.length,true);w.setUint32(24,body.length,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);central.push(c,name);offset+=30+name.length+body.length;}const end=new Uint8Array(22),v=new DataView(end.buffer),size=central.reduce((a,b)=>a+b.length,0);v.setUint32(0,0x06054b50,true);v.setUint16(8,Object.keys(files).length,true);v.setUint16(10,Object.keys(files).length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);return new Blob([...chunks,...central,end]);}
 const image=url=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Could not load a report image.'));im.src=url;});
 async function photoBytes(url){const im=await image(url),c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);const blob=await new Promise(r=>c.toBlob(r,'image/png'));return new Uint8Array(await blob.arrayBuffer());}
 async function excel(p,s,b){
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rels='http://schemas.openxmlformats.org/package/2006/relationships',rows=new Map(),merges=[],heights=new Map();
 const set=(r,c,v,style=0)=>{if(!rows.has(r))rows.set(r,[]);rows.get(r).push({c,v,style});};const merge=(a)=>merges.push(a),col=c=>String.fromCharCode(65+c),title=(r,text,style=1)=>{set(r,0,text,style);merge(`A${r}:I${r}`);heights.set(r,22)};
 for(let r=1;r<=4;r++)heights.set(r,65);
 title(5,'PROGRESS REPORT CARD — '+p.term.toUpperCase());set(6,0,'Student Name:',2);merge('A6:B6');set(6,2,name(s),3);merge('C6:H6');set(6,8,s.photo?'':'PHOTO',2);merge('I6:I9');set(7,0,'Academic Year:',2);merge('A7:B7');set(7,2,p.year,3);merge('C7:D7');set(7,4,'Standard:',2);merge('E7:F7');set(7,6,p.class,2);merge('G7:H7');set(8,0,'Branch:',2);merge('A8:B8');set(8,2,b.name,3);merge('C8:H8');set(9,0,'Admission no.:',2);merge('A9:B9');set(9,2,s.admission||'',3);merge('C9:H9');for(let r=6;r<=9;r++)heights.set(r,24);
 title(10,'STATEMENT OF MARKS');set(12,0,'Subject',2);merge('A12:A13');['Marks — Orals','Marks — Written','Assignments','Total Marks'].forEach((v,i)=>{set(12,1+i*2,v,2);merge(`${col(1+i*2)}12:${col(2+i*2)}12`);set(13,1+i*2,'achieved',2);set(13,2+i*2,'out of',2)});
 let r=14;for(const sub of p.subjects){set(r,0,sub.name,3);Performance.components.forEach((k,i)=>{set(r,1+i*2,sub[k]>0?sub.marks[k]??'—':'—',4);set(r,2+i*2,sub[k]||'—',4)});const complete=Performance.components.every(k=>sub[k]===0||sub.marks[k]!==null);set(r,7,complete?cents(Performance.components.reduce((n,k)=>n+(sub.marks[k]||0),0)):'—',4);set(r,8,cents(Performance.components.reduce((n,k)=>n+sub[k],0)),4);heights.set(r,22);r++;}
 const t=Performance.totals(p);title(r++,`Total: ${t.achieved} / ${t.max}     Percentage: ${t.complete?t.percentage+'%':'Incomplete'}     Grade Achieved: ${t.grade}`);title(r++,'GRADING CODE FOR ACADEMIC RECORD',5);title(r++,'91–100% A+       81–90% A       71–80% B+       61–70% B',5);title(r++,'51–60% C+       41–50% C       35–40% D       0–34% F',5);r++;title(r++,'OBSERVATIONS & REMARKS');title(r++,'GRADING CODE FOR PERSONAL AND SOCIAL DEVELOPMENT',5);title(r++,'AL — Always      ST — Sometimes      NV — Never      R — Rarely',5);set(r,0,'PERSONAL / SOCIAL DEVELOPMENT',2);merge(`A${r}:F${r}`);set(r,6,'GRADE',2);merge(`G${r}:I${r}`);r++;
 for(let i=0;i<Performance.traits.length;i++){set(r,0,Performance.traits[i],3);merge(`A${r}:F${r}`);set(r,6,p.observations[i]||'',4);merge(`G${r}:I${r}`);heights.set(r,21);r++;}
 title(r++,'Remarks: '+p.remarks,3);heights.set(r-1,Math.min(300,Math.max(40,Math.ceil(p.remarks.length/85)*16)));r++;title(r++,'School Incharge: '+p.incharge,3);title(r++,'Signature: ______________________________',3);title(r++,'Date: '+p.date,3);
 r++;for(const address of SchoolDocuments.addresses){title(r++,address,5);heights.set(r-1,28);}
 const last=r,cell=e=>{const ref=col(e.c);return typeof e.v==='number'?`<c r="${ref}" s="${e.style}"><v>${e.v}</v></c>`:`<c r="${ref}" s="${e.style}" t="inlineStr"><is><t xml:space="preserve">${x(e.v)}</t></is></c>`};
 const sheet=`<?xml version="1.0"?><worksheet xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:I${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><cols><col min="1" max="1" width="19" customWidth="1"/><col min="2" max="9" width="10" customWidth="1"/></cols><sheetData>${Array.from({length:last},(_,i)=>{const rn=i+1;return `<row r="${rn}" ht="${heights.get(rn)||20}" customHeight="1">${(rows.get(rn)||[]).map(e=>cell(e).replace(/r="([A-I])"/,`r="$1${rn}"`)).join('')}</row>`}).join('')}</sheetData><mergeCells count="${merges.length}">${merges.map(a=>`<mergeCell ref="${a}"/>`).join('')}</mergeCells><pageMargins left="0.25" right="0.25" top="0.25" bottom="0.25" header="0" footer="0"/><pageSetup paperSize="9" orientation="portrait" fitToWidth="1" fitToHeight="${p.subjects.length<=8&&p.remarks.length<=400?1:0}"/><drawing r:id="rId1"/></worksheet>`;
 const photo=s.photo?await photoBytes(s.photo):null;
 const anchor=(id,colN,rowN,w,h,target)=>`<xdr:oneCellAnchor><xdr:from><xdr:col>${colN}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${rowN}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="${w*9525}" cy="${h*9525}"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${id}" name="${target}"/><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId${id}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`;
 let photoAnchor='';if(photo){const im=await image(s.photo),scale=Math.min(74/im.naturalWidth,118/im.naturalHeight);photoAnchor=anchor(2,8,5,Math.round(im.naturalWidth*scale),Math.round(im.naturalHeight*scale),'Student photo');}
 const files={
 '[Content_Types].xml':`<?xml version="1.0"?><Types xmlns="${'http://schemas.openxmlformats.org/package/2006/content-types'}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Default Extension="png" ContentType="image/png"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/></Types>`,
 '_rels/.rels':`<Relationships xmlns="${rels}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
 'xl/workbook.xml':`<workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Progress report" sheetId="1" r:id="rId1"/></sheets><definedNames><definedName name="_xlnm.Print_Area" localSheetId="0">'Progress report'!$A$1:$I$${last}</definedName></definedNames></workbook>`,
 'xl/_rels/workbook.xml.rels':`<Relationships xmlns="${rels}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
 'xl/styles.xml':`<styleSheet xmlns="${ns}"><fonts count="3"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font><font><sz val="9"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="2"><border/><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6">${[[0,0,'left'],[1,0,'center'],[1,1,'center'],[0,1,'left'],[0,1,'center'],[2,0,'center']].map(([font,border,align])=>`<xf numFmtId="0" fontId="${font}" fillId="0" borderId="${border}" xfId="0" applyAlignment="1"><alignment horizontal="${align}" vertical="center" wrapText="1"/></xf>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`,
 'xl/worksheets/sheet1.xml':sheet,
 'xl/worksheets/_rels/sheet1.xml.rels':`<Relationships xmlns="${rels}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>`,
 'xl/drawings/drawing1.xml':`<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">${anchor(1,0,0,600,Math.round(600*694/1280),'Little Wings Preschool logo')}${photoAnchor}</xdr:wsDr>`,
 'xl/drawings/_rels/drawing1.xml.rels':`<Relationships xmlns="${rels}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/logo.jpg"/>${photo?'<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/photo.png"/>':''}</Relationships>`,
 'xl/media/logo.jpg':await bytes(logo)
 };if(photo)files['xl/media/photo.png']=photo;return zip(files);
 }
 // Download a real PDF rather than relying on the device's print service.
 function jpegPDF(pages,width,height){const objects=[],add=body=>{objects.push(body);return objects.length;};add('<< /Type /Catalog /Pages 2 0 R >>');add('');const pageIds=[];for(const jpg of pages){const imageId=add([enc.encode(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`),jpg,enc.encode('\nendstream')]);const content='q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ';const contentId=add(`<< /Length ${enc.encode(content).length} >>\nstream\n${content}\nendstream`);pageIds.push(add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`));}objects[1]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(i=>i+' 0 R').join(' ')}] >>`;const chunks=[enc.encode('%PDF-1.4\n')],offsets=[0];let offset=chunks[0].length;objects.forEach((obj,i)=>{offsets.push(offset);const pieces=[enc.encode(`${i+1} 0 obj\n`),...(Array.isArray(obj)?obj:[enc.encode(obj)]),enc.encode('\nendobj\n')];for(const piece of pieces){chunks.push(piece);offset+=piece.length}});const xref=offset;chunks.push(enc.encode(`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return new Blob(chunks,{type:'application/pdf'});}
 async function pdf(p,s,b){const logoIm=await image(logo),photo=s.photo?await image(s.photo):null,W=1240,H=1754,pages=[],canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d'),margin=70,right=W-margin;let y=0;
 const text=(v,x,y,size=19,bold=false,max=1100)=>{ctx.font=`${bold?'bold ':''}${size}px Arial`;ctx.fillStyle='#111';ctx.fillText(String(v??''),x,y,max);};
 const line=(y)=>{ctx.beginPath();ctx.moveTo(margin,y);ctx.lineTo(right,y);ctx.strokeStyle='#333';ctx.stroke()};
 const page=()=>{ctx.fillStyle='white';ctx.fillRect(0,0,W,H);const width=520,height=width*logoIm.naturalHeight/logoIm.naturalWidth;ctx.drawImage(logoIm,(W-width)/2,35,width,height);y=45+height;text('PROGRESS REPORT CARD — '+p.term.toUpperCase(),margin,y+22,22,true);y+=40;text('Student Name: '+name(s),margin,y,21,true,850);text('Academic Year: '+p.year+'    Standard: '+p.class,margin,y+29,19,false,850);text('Branch: '+b.name,margin,y+57,19,false,850);text('Admission no.: '+(s.admission||'—'),margin,y+85,18,false,850);if(photo){const scale=Math.min(110/photo.naturalWidth,110/photo.naturalHeight);ctx.drawImage(photo,right-115,y-20,photo.naturalWidth*scale,photo.naturalHeight*scale)}else{ctx.strokeRect(right-115,y-20,110,110);text('PHOTO',right-99,y+42,16)}y+=110;};
 const save=async()=>{SchoolDocuments.footerCanvas(ctx,W,H);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',0.96));if(!blob)throw Error('PDF rendering failed.');pages.push(new Uint8Array(await blob.arrayBuffer()));};
 const room=async h=>{if(y+h>H-125){await save();page();}};
 const center=(v,y,size=18)=>{ctx.font=`bold ${size}px Arial`;ctx.fillStyle='#111';ctx.textAlign='center';ctx.fillText(v,W/2,y,right-margin);ctx.textAlign='left';};
 page();center('STATEMENT OF MARKS',y+20);y+=38;const widths=[290,...Array(8).fill((right-margin-290)/8)],xs=[margin];for(const w of widths)xs.push(xs.at(-1)+w);
 const cells=(values,height=32,bold=false)=>{for(let i=0;i<values.length;i++){ctx.strokeStyle='#444';ctx.strokeRect(xs[i],y,widths[i],height);text(values[i],xs[i]+6,y+height*.68,17,bold,widths[i]-12)}y+=height;};
 const marksHeader=()=>{cells(['Subject','Orals','','Written','','Assignments','','Total',''],32,true);cells(['','achieved','out of','achieved','out of','achieved','out of','achieved','out of'],30,true);};marksHeader();
 for(const sub of p.subjects){if(y+32>H-125){await save();page();center('STATEMENT OF MARKS — continued',y+20);y+=38;marksHeader();}const complete=Performance.components.every(k=>sub[k]===0||sub.marks[k]!==null);cells([sub.name,...Performance.components.flatMap(k=>[sub[k]>0?sub.marks[k]??'—':'—',sub[k]||'—']),complete?cents(Performance.components.reduce((n,k)=>n+(sub.marks[k]||0),0)):'—',cents(Performance.components.reduce((n,k)=>n+sub[k],0))]);}
 const t=Performance.totals(p);await room(120);y+=26;text(`Total: ${t.achieved} / ${t.max}     Percentage: ${t.complete?t.percentage+'%':'Incomplete'}     Grade Achieved: ${t.grade}`,margin,y,19,true);y+=30;center('GRADING CODE FOR ACADEMIC RECORD',y,16);y+=24;text('91–100% A+     81–90% A     71–80% B+     61–70% B',margin,y,17);y+=24;text('51–60% C+     41–50% C     35–40% D     0–34% F',margin,y,17);y+=30;
 await room(100);center('OBSERVATIONS & REMARKS',y,19);y+=25;text('AL — Always      ST — Sometimes      NV — Never      R — Rarely',margin,y,17);y+=14;
 for(let i=0;i<Performance.traits.length;i++){await room(29);ctx.strokeRect(margin,y,right-margin-105,29);ctx.strokeRect(right-105,y,105,29);text(Performance.traits[i],margin+8,y+20,18,false,right-margin-125);text(p.observations[i]||'',right-78,y+20,18,true);y+=29;}
 // Wrap every remark line, including long words, and paginate without truncation.
 const wrap=v=>{ctx.font='18px Arial';const lines=[];for(const paragraph of String(v).split('\n')){let line='';for(const ch of paragraph){if(ctx.measureText(line+ch).width>right-margin){lines.push(line);line=ch}else line+=ch;}lines.push(line);}return lines;};y+=25;for(const v of wrap('Remarks: '+p.remarks)){await room(24);text(v,margin,y,18);y+=24;}if(!p.remarks.trim()){await room(72);y+=72;}await room(95);y+=25;text('School Incharge: '+p.incharge,margin,y,18);y+=30;text('Signature: ___________________________',margin,y,18);text('Date: '+p.date,right-260,y,18);await save();return jpegPDF(pages,W,H);}
 return{excel,pdf,jpegPDF};
})();
