'use strict';
const Performance=(()=>{
 const traits=['Listens attentively','Listens to others without interruptions','Follows directions','Works without constant supervision','Completes tasks','Takes care of materials','Expresses self creatively','Observes, questions, explores','Takes care of personal needs (zipping etc.)','Takes pride in his/her accomplishments','Uses appropriate manners','Shows positive attitude','Gets along well with other children','Participates in group activities','Exercises self control','Respects rights and property of others','Accepts correction'];
 const components=['oral','written','assignment'];
 const defaults=()=>['English','Maths','Drawing','Hindi','EVS'].map((name,i)=>({id:'template-'+i,name,oral:i===2?0:10,written:30,assignment:10}));
 function normalize(d){if(d){d.subjectMasters??=[];d.performance??=[];}}
 function subjectValidate(subjects){if(!Array.isArray(subjects)||!subjects.length||subjects.length>20)throw Error('Set between 1 and 20 subjects.');const ids=new Set(),names=new Set();for(const s of subjects){if(!s||typeof s.id!=='string'||ids.has(s.id)||typeof s.name!=='string'||!s.name.trim()||s.name.length>100||names.has(s.name.trim().toLowerCase())||components.some(k=>!Number.isFinite(s[k])||s[k]<0||s[k]>1000)||components.reduce((a,k)=>a+s[k],0)<=0)throw Error('Subjects need unique names and valid maximum marks.');ids.add(s.id);names.add(s.name.trim().toLowerCase());}}
 function validate(d){normalize(d);if(!Array.isArray(d.subjectMasters)||!Array.isArray(d.performance))throw Error('Invalid performance data');const keys=new Set();for(const m of d.subjectMasters){const k=m.branchId+'|'+m.year+'|'+m.class;if(!d.branches.some(b=>b.id===m.branchId)||!d.years[m.year]||!classes.includes(m.class)||keys.has(k))throw Error('Invalid subject master');keys.add(k);subjectValidate(m.subjects);}
 const pkeys=new Set(),ids=new Set();for(const p of d.performance){const s=d.students.find(s=>s.id===p.studentId),key=p.studentId+'|'+String(p.term).trim().toLowerCase();if(!s||s.branchId!==p.branchId||s.year!==p.year||!classes.includes(p.class)||ids.has(p.id)||typeof p.id!=='string'||typeof p.term!=='string'||!p.term.trim()||p.term.length>60||!Admin.dateOK(p.date)||pkeys.has(key)||!p.observations||typeof p.observations!=='object'||typeof p.remarks!=='string'||typeof p.incharge!=='string')throw Error('Invalid performance record');ids.add(p.id);pkeys.add(key);subjectValidate(p.subjects);for(const sub of p.subjects)for(const k of components)if(sub.marks?.[k]!==null&&(!Number.isFinite(sub.marks?.[k])||sub.marks[k]<0||sub.marks[k]>sub[k]))throw Error('Achieved marks must be between zero and the maximum.');for(const [k,v] of Object.entries(p.observations))if(!/^\d+$/.test(k)||Number(k)>=traits.length||!['','AL','ST','NV','R'].includes(v))throw Error('Invalid observation grade');}
 }
 function master(d,branchId,year,cls){return d.subjectMasters.find(m=>m.branchId===branchId&&m.year===year&&m.class===cls)?.subjects||defaults();}
 const round=n=>Math.round((n+Number.EPSILON)*100)/100;
 function totals(p){let achieved=0,max=0,complete=true;for(const s of p.subjects)for(const k of components){max+=s[k];if(s[k]>0&&s.marks[k]===null)complete=false;achieved+=s.marks[k]||0;}const percentage=max?round(achieved/max*100):0;const band=Math.ceil((max?achieved/max*100:0)-1e-9);const grade=!complete?'Pending':band>=91?'A+':band>=81?'A':band>=71?'B+':band>=61?'B':band>=51?'C+':band>=41?'C':band>=35?'D':'F';return{achieved:round(achieved),max:round(max),percentage,grade,complete};}
 function changes(before,after){const out=[];for(const m of after.subjectMasters){const old=before.subjectMasters.find(x=>x.branchId===m.branchId&&x.year===m.year&&x.class===m.class);if(JSON.stringify(old)!==JSON.stringify(m))out.push(History.event(after.datasetId,'Class subjects updated',m.class,'Branch: '+after.branches.find(b=>b.id===m.branchId)?.name+'; '+m.subjects.map(s=>s.name).join(', '),m.year));}for(const p of after.performance){const old=before.performance.find(x=>x.id===p.id);if(JSON.stringify(old)!==JSON.stringify(p))out.push(History.event(after.datasetId,old?'Performance updated':'Performance recorded',name(after.students.find(s=>s.id===p.studentId)),'Branch: '+after.branches.find(b=>b.id===p.branchId)?.name+'; '+p.term,p.year));}for(const p of before.performance)if(!after.performance.some(x=>x.id===p.id))out.push(History.event(after.datasetId,'Performance deleted',before.students.find(s=>s.id===p.studentId)?.first||p.studentId,p.term,p.year));return out;}
 return{traits,components,defaults,normalize,validate,subjectValidate,master,totals,changes};
})();
