const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>el(s).events.submit({preventDefault(){},target:o})}}

(async()=>{const {x,el,run,submit}=setup();await Promise.resolve();let closed=0;el('#editor').showModal=()=>{el('#editor').open=true};el('#editor').close=()=>{el('#editor').open=false;closed++};const form={branchId:run('Admin.MAIN'),first:'Student',class:'Playgroup',date:'2026-10-10',discount:'0',mobile:'0123',photoFile:{size:0}};
run('openStudent()');await submit('#studentForm',{...form,first:''});assert.match(el('#admissionNotice').textContent,/first name/);assert.equal(el('#admissionNotice').hidden,false);assert.equal(run('data.students.length'),0);assert.equal(closed,0);
await submit('#studentForm',{...form,mobile:''});assert.match(el('#admissionNotice').textContent,/mobile/);await submit('#studentForm',{...form,discount:'1'});assert.match(el('#admissionNotice').textContent,/Discount cannot exceed/);assert.match(el('#admissionNotice').textContent,/Admin/);
await submit('#studentForm',{...form,photoFile:{size:1048577,type:'image/jpeg'}});assert.match(el('#admissionNotice').textContent,/1 MB/);assert.equal(run('data.students.length'),0);
x.FileReader=class{readAsDataURL(){this.onerror()}};await submit('#studentForm',{...form,photoFile:{size:100,type:'image/jpeg'}});assert.match(el('#admissionNotice').textContent,/photo could not be read/);assert.equal(el('#saveAdmissionButton').disabled,false);
run('OneDrive.setEnabled(true);cloudLoaded=false');await submit('#studentForm',form);assert.match(el('#admissionNotice').textContent,/OneDrive records have not been loaded/);
run("cloudLoaded=true;OneDrive.write=async()=>{throw Error('The cloud file changed. Reload cloud data.')} ");await submit('#studentForm',form);assert.match(el('#admissionNotice').textContent,/cloud file changed/);assert.equal(el('#admissionNotice').hidden,false);assert.equal(run('data.students.length'),0);assert.equal(el('#saveAdmissionButton').disabled,false);assert.equal(el('#editor').open,true);
run('OneDrive.setEnabled(false)');await submit('#studentForm',form);assert.equal(run('data.students.length'),1);assert.equal(closed,1);assert.equal(run('tab'),'students');assert.match(el('#notice').textContent,/Admission saved/);
// A missing File object does not break a no-photo admission.
run('openStudent()');await submit('#studentForm',{...form,photoFile:null});assert.equal(run('data.students.length'),2);
// Native HTML validation also supplies an in-dialog explanation.
el('#studentForm').events.invalid({target:{name:'mobile',validationMessage:'Please fill out this field.',closest:()=>({firstChild:{textContent:'Mobile number *'}})}});assert.match(el('#admissionNotice').textContent,/Mobile number: Please fill out/);
// Prevent repeated taps from creating multiple records during a slow cloud save.
run('openStudent();OneDrive.setEnabled(true);cloudLoaded=true;OneDrive.write=()=>new Promise(resolve=>{globalThis.release=resolve})');const p=submit('#studentForm',form);for(let i=0;i<10&&!x.release;i++)await Promise.resolve();assert.equal(el('#saveAdmissionButton').disabled,true);await submit('#studentForm',form);x.release();await p;assert.equal(run('data.students.length'),3);assert.equal(el('#saveAdmissionButton').disabled,false);
console.log('PASS: in-dialog validation/storage errors, missing/oversize/unreadable photos, OneDrive setup and conflict failures, retained form on failure, successful close and Admissions navigation, native invalid messages and duplicate-tap guard');
})().catch(e=>{console.error(e);process.exitCode=1});
