const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>el(s).events.submit({preventDefault(){},target:o})}}

(async()=>{
 const {x,el,run,submit}=setup();await Promise.resolve();
 assert.equal(run('data.branches[0].name'),'Select branch');
 await submit('#branchForm',{code:'B2',name:'Second branch',manager:'Manager',phone:'0123'});
 assert.equal(run('data.branches.length'),2);const bid=run('data.branches[1].id');
 await run(`commit((()=>{const n=clone();n.years[year].fees.Playgroup=1000;n.branches[1].fees[year]={...n.years[year].fees,Playgroup:2000};n.students.push({id:uid(),branchId:Admin.MAIN,year,class:'Playgroup',first:'Main',discount:100},{id:uid(),branchId:'${bid}',year,class:'Playgroup',first:'Second',discount:200});n.payments.push({id:uid(),student:n.students[1].id,date:today(),amount:500,method:'Cash'});return n})())`);
 assert.equal(run('rows().length'),1);assert.equal(run('net(data.students[0])'),900);assert.equal(run('balance(data.students[1])'),1300);
 run(`branchId='${bid}';tab='staff';render()`);
 await submit('#staffForm',{code:'T1',name:'Teacher',role:'Teacher',joined:'2026-01-01',salary:'20000',status:'Active'});
 assert.equal(run('branchStaff().length'),1);const staffid=run('data.staff[0].id');
 for(const [type,amount] of [['Advance',3000],['Advance repayment',1000],['Deduction',500],['Salary adjustment',200],['Salary payment',15000]])await submit('#staffEntryForm',{staffId:staffid,type,amount:String(amount),date:'2026-10-10',month:'2026-10'});
 assert.equal(run("staffPayroll(data.staff[0],'2026-10').net"),18700);assert.equal(run("staffPayroll(data.staff[0],'2026-10').due"),3700);assert.equal(run("staffPayroll(data.staff[0],'2026-10').advanceBalance"),2000);
 const cnt=run('data.staffEntries.length');await submit('#staffEntryForm',{staffId:staffid,type:'Advance repayment',amount:'5000',date:'2026-10-10',month:'2026-10'});assert.equal(run('data.staffEntries.length'),cnt);
 run("salaryMonth='2026-10';adminSection='salary';render()");await el('#freezeSalary').events.click();await run('commit((()=>{const n=clone();n.staff[0].salary=30000;return n})())');assert.equal(run("staffPayroll(data.staff[0],'2026-10').base"),20000);assert.equal(run("staffPayroll(data.staff[0],'2026-11').base"),30000);
 run("tab='attendance';attendanceDate='2026-10-10';render()");await submit('#attendanceForm',{['status_'+staffid]:'Present',['notes_'+staffid]:'On time'});assert.equal(run('data.attendance.length'),1);await submit('#attendanceForm',{['status_'+staffid]:'Half day'});assert.equal(run('data.attendance.length'),1);assert.equal(run('data.attendance[0].status'),'Half day');
 const copy=run('clone()');copy.attendance.push({...copy.attendance[0],id:webcrypto.randomUUID()});x.invalid=copy;assert.throws(()=>run('validate(globalThis.invalid)'),/attendance/);
 await run(`adminClick({dataset:{branchArchive:'${bid}'}})`);assert.equal(run('currentBranch().archived'),true);await submit('#staffForm',{code:'T2',name:'No save',joined:'2026-01-01',salary:'10000',status:'Active'});assert.equal(run('data.staff.length'),1);assert.equal(await run('deletePayment(data.payments[0].id)'),false);
 await run(`adminClick({dataset:{branchDelete:'${bid}'}})`);assert.equal(run('data.branches.length'),1);assert.equal(run('data.students.length'),1);assert.equal(run('data.payments.length'),0);assert.equal(run('data.staff.length'),0);assert.equal(run('data.salarySnapshots.length'),0);const tomb=run("data.deletedRecords.find(x=>x.kind==='branch').id");await run(`restoreDeleted('${tomb}')`);assert.equal(run('data.staff.length'),1);assert.equal(run('data.attendance.length'),1);assert.equal(run('data.salarySnapshots.length'),1);assert.equal(run('data.payments.length'),1);
 assert(run("data.activities.some(e=>e.action==='Branch archived')"));assert(run("data.activities.some(e=>e.action==='Attendance updated')"));
 // Verify reset empties the remote payload, including pending and deleted history.
 run("OneDrive.setEnabled(true);cloudLoaded=true;cloudRevision=data.revision;OneDrive.write=async d=>{globalThis.remote=structuredClone(d)}");x.prompt=()=> 'RESET ALL';const oldDataset=run('data.datasetId');await run('resetLedger()');assert.equal(x.remote.students.length,0);assert.equal(x.remote.staff.length,0);assert.equal(x.remote.staffEntries.length,0);assert.equal(x.remote.attendance.length,0);assert.equal(x.remote.salarySnapshots.length,0);assert.equal(x.remote.deletedRecords.length,0);assert.equal(x.remote.activities.length,0);assert.equal(run('History.pending().length'),0);assert.notEqual(x.remote.datasetId,oldDataset);assert.equal(x.remote.branches.length,1);
 // Reset never clears local records or logs when the remote write fails.
 await run("commit((()=>{const n=clone();n.school='Must remain';return n})())");const before=run('data.revision');run("OneDrive.write=async()=>{throw Error('conflict')}");await run('resetLedger()');assert.equal(run('data.revision'),before);assert.equal(run('data.school'),'Must remain');
 console.log('PASS: legacy branch migration, isolated admissions/fees, staff transactions and balances, advance repayment limit, salary snapshots, attendance update/uniqueness, archived write guards, branch cascade restore and atomic cloud reset');
})().catch(e=>{console.error(e);process.exitCode=1});
