const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['bootstrap.js','cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','school-documents.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>el(s).events.submit({preventDefault(){},target:o})}}

(async()=>{const {x,el,run,submit}=setup();await Promise.resolve();el('#editor').showModal=()=>{};el('#editor').close=()=>{};const form={branchId:run('Admin.MAIN'),first:'Student',gender:'Male',class:'Playgroup',date:'2026-10-10',discount:'0',mobile:'0123',admission:'MANUAL',photoFile:{size:0}};
run('openStudent()');assert.match(el('#fields').innerHTML,/MAIN-2026-2027-0001/);assert.match(el('#fields').innerHTML,/readonly/);assert.equal(run('Object.keys(data.admissionSequences).length'),0);
await submit('#studentForm',form);assert.equal(run('data.students[0].admission'),'MAIN-2026-2027-0001');await submit('#studentForm',form);assert.equal(run('data.students[1].admission'),'MAIN-2026-2027-0002');
const sid=run('data.students[1].id');run(`editing='${sid}'`);await submit('#studentForm',{...form,first:'Edited',admission:'FORGED'});assert.equal(run('data.students[1].admission'),'MAIN-2026-2027-0002');run('editing=null');
await run(`deleteStudent('${sid}')`);await submit('#studentForm',form);assert.equal(run('data.students.at(-1).admission'),'MAIN-2026-2027-0003');
await submit('#branchForm',{code:'LW02',name:'Second'});const bid=run('data.branches[1].id');run('openStudent()');el('#studentForm [name=branchId]').value=bid;run('updateAdmissionPreview()');assert.equal(el('#studentForm [name=admission]').value,'LW02-2026-2027-0001');await submit('#studentForm',{...form,branchId:bid});assert.equal(run('data.students.at(-1).admission'),'LW02-2026-2027-0001');
// Branch-code changes affect new numbers, preserving the sequence and old IDs.
await run(`commit((()=>{const n=clone();n.branches[1].code='LW03';return n})())`);await submit('#studentForm',{...form,branchId:bid});assert.equal(run('data.students.at(-1).admission'),'LW03-2026-2027-0002');
await run(`commit((()=>{const n=clone();n.years['2027–2028']={fees:{...n.years[year].fees}};return n})())`);await run(`carry(data.students.at(-1).id)`);assert.equal(run('data.students.at(-1).admission'),'LW03-2027-2028-0001');
// A failed remote save consumes no number.
run("editing=null;OneDrive.setEnabled(true);cloudLoaded=true;OneDrive.write=async()=>{throw Error('offline')}");const count=run('data.students.length'),seq=run('JSON.stringify(data.admissionSequences)');await submit('#studentForm',{...form,branchId:bid});assert.equal(run('data.students.length'),count);assert.equal(run('JSON.stringify(data.admissionSequences)'),seq);
// Legacy backup without counters infers the next sequence, including deleted copies.
run('OneDrive.setEnabled(false)');const copy=run('clone()');delete copy.admissionSequences;x.backup=copy;run('validate(globalThis.backup)');assert.equal(run(`Admissions.next(globalThis.backup,'${bid}','2026–2027')`),'LW03-2026-2027-0003');
console.log('PASS: readonly automatic admission numbers, branch/year prefixes, independent sequences, immutable edits, deleted-number reservation, branch-code changes, next-year enrolment, failed-save preservation and backup migration');
})().catch(e=>{console.error(e);process.exitCode=1});
