const outputPath=f=>require('path').join(process.env.TEST_OUTPUT_DIR||require('os').tmpdir(),f);
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['bootstrap.js','cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','school-documents.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>{Object.assign(el(s),o);return el(s).events.submit({preventDefault(){},target:o})}}}

(async()=>{const {x,el,run,submit}=setup();await Promise.resolve();
await run("commit((()=>{const n=clone();n.students.push({id:uid(),branchId:Admin.MAIN,year,class:'Jr. Kg',first:'Synthetic',middle:'Sample',surname:'Student',father:'Sample Father',mother:'Sample Mother',dob:'2021-06-04',discount:0,admission:'T1'});return n})())");
run("navigateTo('certificates')");assert.match(el('#view').innerHTML,/certificateForm/);assert.equal(run("groupForTab('certificates')"),'students');
const form={student:run('data.students[0].id'),date:'2026-06-25',place:'Badlapur',principal:'Deepti Sarma',status:'is'};
await submit('#certificateForm',form);assert.match(el('#view').innerHTML,/BONAFIDE CERTIFICATE/);assert.match(el('#view').innerHTML,/04 June 2021/);assert.match(el('#view').innerHTML,/Sample Father/);assert.match(el('#view').innerHTML,/Sample Mother/);assert.match(el('#view').innerHTML,/2026-27/);
for(const a of run('SchoolDocuments.addresses'))assert(el('#view').innerHTML.includes(a.replace(/&/g,'&amp;')));
run("certificateClass='Nursery';render()");assert.match(el('#view').innerHTML,/No students/);run("certificateClass='';render()");
assert.throws(()=>run("SchoolDocuments.details({...data.students[0],dob:''},certificateOptions)"),/date of birth/);
assert.throws(()=>run("SchoolDocuments.details(data.students[0],{...certificateOptions,date:'2026-02-30'})"),/valid date/);
const draws=[];const ctx={font:'',fillStyle:'',textAlign:'',strokeStyle:'',fillRect(){},drawImage(){},strokeRect(){},fillText(t,x,y){draws.push({t:String(t),x,y})},measureText(t){return{width:String(t).length*12}}};const jpg=fs.readFileSync(require('path').join(__dirname,'../assets/little-wings-logo.jpg'));
x.Image=class{constructor(){this.naturalWidth=1280;this.naturalHeight=694}set src(v){this.onload()}};x.document.createElement=()=>({getContext:()=>ctx,toBlob(cb){cb(new Blob([jpg],{type:'image/jpeg'}))}});
const pdf=await run('SchoolDocuments.pdf(SchoolDocuments.details(data.students[0],certificateOptions))');assert.equal(pdf.type,'application/pdf');assert((await pdf.text()).startsWith('%PDF-1.4'));assert(draws.some(d=>d.t==='BONAFIDE CERTIFICATE'));for(const a of run('SchoolDocuments.addresses'))assert(draws.some(d=>d.t===a&&d.y>1600));assert(draws.every(d=>d.y<1754));
console.log('PASS: certificate student/class filtering, admission-derived values, exact address footer, date and missing-data validation, PDF content and page bounds');
})().catch(e=>{console.error(e);process.exitCode=1});
