const outputPath=f=>require('path').join(process.env.TEST_OUTPUT_DIR||require('os').tmpdir(),f);
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const navEvents={},stack=[null];let position=0;const fakeHistory={get state(){return stack[position]},pushState(s){stack.splice(position+1);stack.push(structuredClone(s));position++},replaceState(s){stack[position]=structuredClone(s)},back(){if(position){position--;navEvents.popstate?.({state:stack[position]})}},forward(){if(position+1<stack.length){position++;navEvents.popstate?.({state:stack[position]})}}};const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:fakeHistory,btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;x.addEventListener=(k,f)=>navEvents[k]=f;vm.createContext(x);for(const f of ['bootstrap.js','cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','school-documents.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>{Object.assign(el(s),o);return el(s).events.submit({preventDefault(){},target:o})}}}

(async()=>{const {x,el,run}=setup();await Promise.resolve();assert.equal(run('tab'),'summary');assert.equal(x.history.state.index,0);assert.equal(el('#appBack').disabled,true);
run("navigateTo('students');navigateTo('fees')");assert.equal(x.history.state.index,2);x.history.back();assert.equal(run('tab'),'students');x.history.forward();assert.equal(run('tab'),'fees');
run("navigateTo('staff');navigateTo('attendance')");el('#appBack').onclick();assert.equal(run('tab'),'staff');el('#appHome').onclick();assert.equal(run('tab'),'summary');x.history.back();assert.equal(run('tab'),'staff');
run("navigateTo('students');setTopClass('Nursery');render();navigateTo('parents');setTopClass('Jr. Kg');render()");x.history.back();assert.equal(run('tab'),'students');assert.equal(run('classFilter'),'Nursery');
await run("commit((()=>{const n=clone();n.students.push({id:uid(),branchId:Admin.MAIN,year,class:'Nursery',first:'History Student',gender:'Male',discount:0});return n})())");run("navigateTo('performance');performanceClick({dataset:{performanceStudent:data.students[0].id}})");assert.match(el('#view').innerHTML,/performance-editor/);el('#performanceBack').events.click();assert.equal(run('performanceStudent'),'');assert(!el('#view').innerHTML.includes('performance-editor'));x.history.forward();assert.match(el('#view').innerHTML,/performance-editor/);
const before=x.history.state.index;run('render();render()');assert.equal(x.history.state.index,before);
el('#editor').open=true;el('#editor').close=()=>el('#editor').open=false;el('#appBack').onclick();assert.equal(el('#editor').open,false);assert.equal(x.history.state.index,before);
console.log('PASS: home Overview, native Back/Forward and app buttons, restored class context, performance form/list history and no duplicate entries on saves/renders');
})().catch(e=>{console.error(e);process.exitCode=1});
