const outputPath=f=>require('path').join(process.env.TEST_OUTPUT_DIR||require('os').tmpdir(),f);
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['bootstrap.js','cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','school-documents.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>{Object.assign(el(s),o);return el(s).events.submit({preventDefault(){},target:o})}}}

(async()=>{const {x,el,run}=setup();await Promise.resolve();
await run(`commit((()=>{const n=clone();n.branches.push({id:uid(),code:'B2',name:'Second Branch',fees:{},archived:true});n.branches[0].fees[year]={...n.years[year].fees,Playgroup:1000};n.branches[1].fees[year]={...n.years[year].fees,Playgroup:2000};n.years['2027–2028']={fees:{...n.years[year].fees}};n.students.push({id:uid(),branchId:n.branches[0].id,year,class:'Playgroup',first:'First',discount:100},{id:uid(),branchId:n.branches[1].id,year,class:'Playgroup',first:'Second',discount:200},{id:uid(),branchId:n.branches[1].id,year:'2027–2028',class:'Playgroup',first:'Later',discount:0});n.payments.push({id:uid(),student:n.students[0].id,date:today(),amount:200,method:'Cash'},{id:uid(),student:n.students[1].id,date:today(),amount:1900,method:'Cash'});return n})())`);
run("navigateTo('summary')");assert.match(el('#branch').innerHTML,/>ALL</);const original=run('branchId');
el('#branch').events.change({target:{value:'ALL'}});assert.equal(run('branchId'),original);assert.equal(run('overviewAll'),true);assert.match(el('#branch').innerHTML,/value="ALL" selected/);assert.match(el('#view').innerHTML,/ALL branches/);assert.match(el('#view').innerHTML,/Branch summary/);assert.match(el('#view').innerHTML,/Second Branch \(archived\)/);assert.match(el('#view').innerHTML,/<strong>2<\/strong>/);assert.match(el('#view').innerHTML,/2,700/);assert.match(el('#view').innerHTML,/2,100/);assert.match(el('#view').innerHTML,/700/);assert.match(el('#view').innerHTML,/100/);assert.equal(el('#add').disabled,true);
run('openStudent()');assert.match(el('#notice').textContent,/Select a branch/);
run('makeWorkbook=sheets=>{globalThis.overviewSheets=sheets;return new Blob([])};download=(...args)=>{globalThis.overviewDownload=args};exportExcel()');assert.deepEqual(Array.from(x.overviewSheets.Overview[1]),['ALL',run('year'),2,2700,2100,700,100]);
run("navigateTo('students')");assert(!el('#branch').innerHTML.includes('value="ALL"'));assert.equal(run('rows().length'),1);assert.equal(el('#add').disabled,false);
run("navigateTo('summary')");el('#branch').events.change({target:{value:original}});assert.equal(run('overviewAll'),false);assert(!el('#view').innerHTML.includes('ALL branches'));assert.match(el('#view').innerHTML,/<strong>1<\/strong>/);
console.log('PASS: ALL overview aggregate by year, branch-specific fee/discount and payment totals, due/credit isolation, archived branch inclusion, Excel totals and safe individual-branch editing');
})().catch(e=>{console.error(e);process.exitCode=1});
