const outputPath=f=>require('path').join(process.env.TEST_OUTPUT_DIR||require('os').tmpdir(),f);
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['bootstrap.js','cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','school-documents.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>{Object.assign(el(s),o);return el(s).events.submit({preventDefault(){},target:o})}}}

(async()=>{const {x,el,run,submit}=setup();await Promise.resolve();
assert.equal(run("Object.keys(navGroups).join(',')"),'students,staff,admin');assert.equal(run("groupForTab('subjects')"),'admin');assert.equal(run("groupForTab('staffmaster')"),'admin');assert.equal(run("groupForTab('performance')"),'students');run("navigateTo('staff')");assert(!el('#view').innerHTML.includes('data-admin-section="master"'));run("navigateTo('staffmaster')");assert(el('#view').innerHTML.includes('id="staffForm"'));
await run(`commit((()=>{const n=clone();n.students.push({id:uid(),branchId:Admin.MAIN,year,class:'Sr. Kg',first:'Synthetic',surname:'Student',discount:0,admission:'T1'});return n})())`);const sid=run('data.students[0].id');run("tab='subjects';render()");
const subjects={};['English','Maths','Drawing','Hindi','EVS'].forEach((s,i)=>{subjects['subject_'+i]=s;subjects['oral_'+i]=i===2?'0':'10';subjects['written_'+i]='30';subjects['assignment_'+i]='10'});await submit('#subjectForm',subjects);assert.equal(run('data.subjectMasters.length'),1);
run("tab='performance';render();performanceClick({dataset:{performanceStudent:data.students[0].id}})");assert.match(el('#view').innerHTML,/Orals achieved/);const form={date:'2026-10-10',incharge:'Teacher',remarks:'Making good progress',observation_0:'AL'};for(let i=0;i<5;i++)for(const k of ['oral','written','assignment'])form['mark_'+i+'_'+k]=k==='oral'&&i===2?'':k==='written'?'30':'10';await submit('#performanceForm',form);assert.equal(run('data.performance.length'),1);assert.equal(run('Performance.totals(data.performance[0]).achieved'),240);assert.equal(run('Performance.totals(data.performance[0]).max'),240);assert.equal(run('Performance.totals(data.performance[0]).grade'),'A+');assert(run("data.activities.some(e=>e.action==='Performance recorded')"));assert.match(el('#view').innerHTML,/assets\/little-wings-logo.jpg/);
// Branch/class roster shows only matching students, with saved term progress.
run('performanceStudent="";render()');assert.match(el('#view').innerHTML,/240 \/ 240/);assert.match(el('#view').innerHTML,/100%/);assert.match(el('#view').innerHTML,/performance-incomplete/);assert.match(el('#view').innerHTML,/In progress/);
const full={...form};for(let i=0;i<17;i++)full['observation_'+i]='AL';
run('performanceClick({dataset:{performanceStudent:data.students[0].id}})');assert.match(el('#view').innerHTML,/performance-editor/);await submit('#performanceForm',full);
run('performanceStudent="";render()');assert.match(el('#view').innerHTML,/performance-complete/);assert.match(el('#view').innerHTML,/1 complete/);
el('#performanceClass').events.change({target:{value:'Nursery'}});assert.match(el('#view').innerHTML,/No students/);assert(!el('#view').innerHTML.includes('data-performance-student='));
el('#performanceClass').events.change({target:{value:'Sr. Kg'}});
run("performanceTerm='Term I';render()");assert.match(el('#view').innerHTML,/Not started/);assert.match(el('#view').innerHTML,/0 \/ 240/);assert(!el('#view').innerHTML.includes('class="performance-name performance-complete"'));
run("performanceTerm='Term II';performanceClick({dataset:{performanceStudent:data.students[0].id}})");
// Empty marks stay missing; zero is an assessed score.
await submit('#performanceForm',{...form,mark_0_oral:''});assert.equal(run('Performance.totals(data.performance[0]).grade'),'Pending');await submit('#performanceForm',{...form,mark_0_oral:'0'});assert.equal(run('Performance.totals(data.performance[0]).complete'),true);
const rev=run('data.revision');await submit('#performanceForm',{...form,mark_0_oral:'11'});assert.equal(run('data.revision'),rev);await submit('#performanceForm',form);
// Subject edits do not change a saved marksheet's maxima.
run("tab='subjects';render()");await submit('#subjectForm',{...subjects,written_0:'100'});assert.equal(run('data.subjectMasters[0].subjects[0].written'),100);assert.equal(run('data.performance[0].subjects[0].written'),30);
// Exact grade thresholds follow the supplied workbook's lookup (35% is D).
for(const [n,expected] of [[0,'F'],[34,'F'],[35,'D'],[40,'D'],[41,'C'],[51,'C+'],[61,'B'],[71,'B+'],[81,'A'],[91,'A+'],[100,'A+']]){x.gradeSample={subjects:[{oral:100,written:0,assignment:0,marks:{oral:n,written:null,assignment:null}}]};assert.equal(run('Performance.totals(globalThis.gradeSample).grade'),expected);}
// Student deletion/restoration carries their performance, as does branch deletion.
await run(`deleteStudent('${sid}')`);assert.equal(run('data.performance.length'),0);await run('restoreDeleted(data.deletedRecords[0].id)');assert.equal(run('data.performance.length'),1);
await submit('#branchForm',{code:'B2',name:'Second'});await run(`commit((()=>{const n=clone();Admin.removeBranch(n,Admin.MAIN);return n})())`);assert.equal(run('data.performance.length'),0);assert.equal(run('data.subjectMasters.length'),0);await run('restoreDeleted(data.deletedRecords.find(x=>x.kind===\'branch\').id)');assert.equal(run('data.performance.length'),1);assert.equal(run('data.subjectMasters.length'),1);
// Formatted workbook embeds exact logo bytes and no sample student's data.
x.fetch=async()=>({ok:true,arrayBuffer:async()=>{const b=fs.readFileSync(require('path').join(__dirname,'../assets/little-wings-logo.jpg'));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}});
const workbook=await run('Marksheet.excel(data.performance[0],data.students[0],data.branches.find(b=>b.id===data.students[0].branchId))');fs.writeFileSync(outputPath('test-progress-report.xlsx'),Buffer.from(await workbook.arrayBuffer()));
// Validate PDF container construction independently of a live browser canvas.
const jpg=fs.readFileSync(require('path').join(__dirname,'../assets/little-wings-logo.jpg'));x.jpg=new Uint8Array(jpg);const pdf=run('Marksheet.jpegPDF([globalThis.jpg,globalThis.jpg],1280,694)');fs.writeFileSync(outputPath('test-progress-report.pdf'),Buffer.from(await pdf.arrayBuffer()));
// Exercise the whole PDF render pipeline with a mock canvas, recording draw positions.
const draws=[];let pageNumber=0;const context={font:'',textAlign:'',fillStyle:'',strokeStyle:'',fillRect(){},drawImage(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},strokeRect(){},fillText(v,xp,yp){draws.push({v:String(v),x:xp,y:yp,page:pageNumber})},measureText(v){return{width:String(v).length*9}}};
x.Image=class{constructor(){this.naturalWidth=1280;this.naturalHeight=694}set src(v){this.onload()}};x.document.createElement=()=>({width:0,height:0,getContext:()=>context,toBlob(cb){pageNumber++;cb(new Blob([jpg],{type:'image/jpeg'}))}});
await run('Marksheet.pdf(data.performance[0],data.students[0],data.branches.find(b=>b.id===data.students[0].branchId))');assert(draws.some(d=>d.v==='Grade Achieved: A+')||draws.some(d=>d.v.includes('Grade Achieved: A+')));for(const trait of run('Performance.traits'))assert(draws.some(d=>d.v===trait));assert(draws.every(d=>d.y<1754));
draws.length=0;pageNumber=0;await run(`Marksheet.pdf((()=>{const p=structuredClone(data.performance[0]);p.subjects=Array.from({length:20},(_,i)=>({...structuredClone(p.subjects[0]),id:'subject-'+i,name:'Subject '+i}));p.remarks='Long remark '.repeat(150);return p})(),data.students[0],data.branches.find(b=>b.id===data.students[0].branchId))`);assert(pageNumber>1);assert(draws.some(d=>d.v==='Subject 19'));for(const trait of run('Performance.traits'))assert(draws.some(d=>d.v===trait));assert(draws.every(d=>d.y<1754));
for(const a of run('SchoolDocuments.addresses')){assert(draws.some(d=>d.v===a));for(let page=0;page<pageNumber;page++)assert(draws.some(d=>d.v===a&&d.page===page));}
const copy=run('clone()');delete copy.subjectMasters;delete copy.performance;x.legacy=copy;run('validate(globalThis.legacy)');assert.equal(copy.performance.length,0);assert.equal(copy.subjectMasters.length,0);
run("OneDrive.setEnabled(true);cloudLoaded=true;OneDrive.write=async d=>{globalThis.remote=structuredClone(d)}");x.prompt=()=> 'RESET ALL';await run('resetLedger()');assert.equal(x.remote.performance.length,0);assert.equal(x.remote.subjectMasters.length,0);assert.equal(x.remote.activities.length,0);
console.log('PASS: grouped navigation, Admin master data, subject setup and frozen report maxima, marks limits and missing scores, grades, cascading performance deletion/restoration, legacy migration and shared reset');
})().catch(e=>{console.error(e);process.exitCode=1});
