const outputPath=f=>require('path').join(process.env.TEST_OUTPUT_DIR||require('os').tmpdir(),f);
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const mem=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
function setup(){const els=new Map();const el=s=>{if(!els.has(s))els.set(s,{textContent:'',innerHTML:'',value:'',events:{},addEventListener(k,f){this.events[k]=f},classList:{toggle(){}},scrollIntoView(){}});return els.get(s)};const x={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,DataView,URL,URLSearchParams,Intl,structuredClone,setTimeout:()=>1,localStorage:mem(),sessionStorage:mem(),location:{origin:'https://school.example',pathname:'/preschoolapp/',search:'',hash:'',protocol:'https:',hostname:'school.example',assign(v){this.assigned=v}},history:{replaceState(){}},btoa:s=>Buffer.from(s,'binary').toString('base64'),alert(){},confirm:()=>true,FormData:class{constructor(o){this.o=o}get(k){return this.o[k]}},document:{querySelector:el,querySelectorAll:()=>[],activeElement:null},indexedDB:{open(){throw Error('Unavailable')}}};x.window=x;vm.createContext(x);for(const f of ['bootstrap.js','cloud.js','history.js','excel.js','admin.js','admin-ui.js','performance.js','performance-ui.js','marksheet-export.js','school-documents.js','navigation.js','admissions.js','app.js'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..',f),'utf8'),x);return{x,el,run:s=>vm.runInContext(s,x),submit:async(s,o)=>{Object.assign(el(s),o);return el(s).events.submit({preventDefault(){},target:o})}}}

(async()=>{const {x,el,run}=setup();await Promise.resolve();
const html=fs.readFileSync(require('path').join(__dirname,'..','index.html'),'utf8');assert(html.indexOf('id="year"')<html.indexOf('id="branch"'));assert.match(html,/<select id="topClass">/);
await run(`commit((()=>{const n=clone();n.branches.push({id:uid(),code:'B2',name:'Second',fees:{},archived:false});n.years['2027–2028']={fees:{...n.years[year].fees}};for(const [branch,cls,studentYear,first] of [[0,'Nursery',year,'Included'],[0,'Jr. Kg',year,'OtherClass'],[1,'Nursery',year,'OtherBranch'],[0,'Nursery','2027–2028','OtherYear']])n.students.push({id:uid(),branchId:n.branches[branch].id,year:studentYear,class:cls,first,gender:'Male',discount:0});return n})())`);
el('#topClass').events.change({target:{value:'Nursery'}});assert.equal(run('classFilter'),'Nursery');assert.equal(run('rows().length'),1);
for(const tab of ['summary','students','parents','fees','reports','performance','certificates']){run("navigateTo('"+tab+"')");assert.equal(run('classFilter'),'Nursery');assert.match(el('#topClass').innerHTML,/<option selected>Nursery/);assert.equal(run('rows()[0].first'),'Included');assert(!el('#view').innerHTML.includes('OtherClass'));assert(!el('#view').innerHTML.includes('OtherBranch'));assert(!el('#view').innerHTML.includes('OtherYear'));}
run("navigateTo('subjects')");assert.equal(run('subjectClass'),'Nursery');assert(!el('#topClass').innerHTML.includes('ALL classes'));
for(const tab of ['staff','attendance','staffmaster','branches','settings','history']){run("navigateTo('"+tab+"')");assert.equal(run('classFilter'),'Nursery');assert.equal(el('#filterScope').hidden,false);assert.match(el('#topClass').innerHTML,/<option selected>Nursery/);}
run("navigateTo('summary')");el('#branch').events.change({target:{value:'ALL'}});assert.match(el('#view').innerHTML,/<strong>2<\/strong>/);
run("navigateTo('students')");el('#branch').events.change({target:{value:run('data.branches[1].id')}});assert.equal(run('rows()[0].first'),'OtherBranch');
el('#year').events.change({target:{value:'2027–2028'}});assert.equal(run('rows().length'),0);el('#branch').events.change({target:{value:run('Admin.MAIN')}});assert.equal(run('rows()[0].first'),'OtherYear');
el('#topClass').events.change({target:{value:''}});assert.equal(run('classFilter'),'');assert.match(el('#topClass').innerHTML,/ALL classes/);
console.log('PASS: shared top branch/class/year selectors, persistent cross-tab class filter, student isolation by class/year/branch, ALL overview class totals, subject context and branch-wide staff hints');
})().catch(e=>{console.error(e);process.exitCode=1});
